#!/bin/sh

start() {
    rm nohup.out 2>&1 > /dev/null
    nohup python3 ./GameServerBot.py 2>&1 &
}

stop() {
    pkill -f GameServerBot.py
}

case $1 in 
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        start
        ;;
    status)
            pgrep -f GameServerBot.py > /dev/null && echo "running" || echo "stopped"
        ;;
    *)
        echo "$0 [start|stop|restart|status]"
    ;;
esac


